import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";

export async function POST(request: Request) {
  try {
    // 1. SECURE: Verify the user is actually authenticated via Next.js
    const session = await getSession();
    if (!session?.sub) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();

    // 2. DATA ENRICHMENT: Map MongoDB user attributes to the API payload
    // You might fetch their specific Wallet UUID from MongoDB here.
    const pythonPayload = {
      source_wallet_id: body.spending_wallet_uuid, // Mapped locally
      savings_wallet_id: body.savings_wallet_uuid, // Mapped locally
      purchase_amount: body.amount,
      mode: body.mode || "Eco",
      idempotency_key: crypto.randomUUID(), // Automatically generated by the BFF
    };

    // 3. PROXY: Make the Server-to-Server call to Python FastAPI
    const backendUrl = process.env.PYTHON_BACKEND_URL || "http://localhost:8000/api/v1";
    const pythonResponse = await fetch(`${backendUrl}/roundups/execute`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // "x-api-key": process.env.PYTHON_CORE_SECRET // Internal security
      },
      body: JSON.stringify(pythonPayload),
    });

    if (!pythonResponse.ok) {
      throw new Error("Core engine failed to process transaction");
    }

    const data = await pythonResponse.json();

    // 4. TRANSLATE: Return exactly what the React UI expects, hiding backend complexity
    return NextResponse.json({
      success: true,
      message: "Round-up applied successfully",
      saved_amount: data.amount
    });

  } catch (error) {
    console.error("[BFF Error]", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
