import type { Metadata } from "next";
import { Cairo, Exo, Sora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { getLocale } from "next-intl/server";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Faka Inviest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={cn(
        "h-full",
        "antialiased",
        cairo.variable,
        exo.variable,
        sora.variable,
      )}
    >
      <body>{children}</body>
    </html>
  );
}
